name = "PasteMyst"
uuid = "b8ba6cf2-bc19-4044-9316-f77e3c6f0f88"
authors = ["Satakun Utama <49134472+lines-of-codes@users.noreply.github.com>"]
version = "0.2.0"

[deps]
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"

[compat]
HTTP = "0.9.12"
JSON = "0.21.0"
julia = "1.0"
